name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cs:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: Coding standard
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Composer Update
        run: composer update

      - name: CS Check
        run: make cs

  phpstan:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: PHPStan lv. 7
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Composer Update
        run: composer update

      - name: PHPStan lv. 7
        run: make phpstan

  unit:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: Unit Tests
    strategy:
      matrix:
        version: [ 8.2, 8.3, 8.4 ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}

      - name: Composer Update
        run: composer update

      - name: Nette Tester
        run: make test

      - name: PHPUnit
        run: make phpunit
